Ingredient.destroy_all

Ingredient.create!(name: "citron" »)
Ingredient.create!(name: "citron vert" »)
Ingredient.create!(name: "glace")
Ingredient.create!(name: "menthe fraîche")
Ingredient.create!(name: "vodka")
Ingredient.create!(name: "rhum")
Ingredient.create!(name: "bière blonde")
Ingredient.create!(name: "sucre de canne" »)
Ingredient.create!(name: "eau gazeuse")
Ingredient.create!(name: "cidre")
Ingredient.create!(name: "fruits rouges")
Ingredient.create!(name: "bière brune")
Ingredient.create!(name: "curaçao bleu")
Ingredient.create!(name: "cointreau")
Ingredient.create!(name: "cranberry")
Ingredient.create!(name: "eau")
Ingredient.create!(name: "eau gazeuse")
Ingredient.create!(name: "rhum")
Ingredient.create!(name: "jus d’ananas")
Ingredient.create!(name: " lait de coco")
Ingredient.create!(name: "tequila")
Ingredient.create!(name: "jus d’orange")
Ingredient.create!(name: "sirop de grenade")
Ingredient.create!(name: "crème de café")
Ingredient.create!(name: "lait entier")
